// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2016 Pikkpoiss
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gamejam

import "fmt"

type EventObserverListID int

var ErrEventObserverNotInList = fmt.Errorf("Could not find item in list")

// A EventObserverNode represents a doubly-linked EventObserver.
type EventObserverNode struct {
	EventObserver
	id   EventObserverListID
	next *EventObserverNode
	prev *EventObserverNode
}

func (n *EventObserverNode) Next() *EventObserverNode {
	return n.next
}

func (n *EventObserverNode) EventObserverListID() EventObserverListID {
	return n.id
}

// Unlinks the node from the current list.
// Returns the next node for convenience while iterating.
func (n *EventObserverNode) Unlink() (next *EventObserverNode) {
	next = n.next
	if n.next != nil {
		n.next.prev = n.prev
	}
	if n.prev != nil {
		n.prev.next = n.next
	}
	n.next = nil
	n.prev = nil
	return
}

// A EventObserverList manages a list of EventObserverNode items.
type EventObserverList struct {
	nextID EventObserverListID
	head   *EventObserverNode
}

func NewEventObserverList(items ...EventObserver) (l *EventObserverList) {
	l = &EventObserverList{
		nextID: 1,
	}
	for i := len(items) - 1; i >= 0; i-- {
		l.Prepend(items[i])
	}
	return
}

func (l *EventObserverList) Head() *EventObserverNode {
	return l.head
}

func (l *EventObserverList) Prepend(item EventObserver) (node *EventObserverNode) {
	var id = l.nextID
	l.nextID++
	node = &EventObserverNode{
		EventObserver: item,
		id:            id,
		next:          l.head,
		prev:          nil,
	}
	if l.head != nil {
		l.head.prev = node
	}
	l.head = node
	return
}

// Attempts to remove `item` from the list.
// Returns ErrEventObserverNotInList if the ID did not exist in list.
func (l *EventObserverList) Remove(id EventObserverListID) (removed EventObserver, err error) {
	var node = l.Head()
	for node != nil {
		if node.EventObserverListID() == id {
			node.Unlink()
			removed = node.EventObserver
			return // Should only ever be one of an ID in a list.
		}
		node = node.Next()
	}
	err = ErrEventObserverNotInList
	return
}

// Unlinks all EventObserver items from this EventObserverList.
func (l *EventObserverList) Empty() {
	var node = l.Head()
	for node != nil {
		node = node.Unlink()
	}
}
